version: '3.7'
services:
    backend:
        container_name: backend-api
        build: ./npf
        env_file:
            - ./npf/.env
        ports:
            - "8000:8000"
#        expose:
#            - "8000"
        volumes:
            - media:/data/media/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 40s
        restart: always

    nginx:
        build: ./nginx
        container_name: nginx
        volumes:
            - media:/usr/share/nginx/html/media/:ro
        restart: always


volumes:
    media: