version: '3.7'

services:
  backend:
    container_name: backend-api
    extends:
      file: docker-compose.base.yml
      service: backend

  nginx:
    container_name: nginx
    extends:
      file: docker-compose.base.yml
      service: nginx
    ports:
      - '80:80'
    depends_on:
      backend:
        condition: service_healthy

volumes:
  static:
  media: